### ISSUE TITLE
Add test cases for authentication

### ISSUE THREAD

**Issue by bhansaliyash** [divyang02/WolfLease#34]
Add test case for authentication application flow

**Comment by bhansaliyash** [comment]
I think authentication flow will be tested when we update the existing test cases for housing application as all apis now require authentication. What do you think @devmehta1999 ?

**Comment by devmehta1999** [comment]
Yes, I do not think we need to add test cases for them separately.

**Comment by divyang02** [comment]
Yes that's correct. I think it's already being tested as reflected in the codecoverage.
