### ISSUE TITLE
Update pending test cases

### ISSUE THREAD

**Issue by divyang02** [divyang02/WolfLease#36]
We need to update the previous test cases in order to reflect the changes we made

**Comment by divyang02** [comment]
@bhansaliyash We should probably create a setup method which can run for each test case and login a user before hand?

**Comment by bhansaliyash** [comment]
Yes.. we will need that as only authenticated user can access the urls now.

**Comment by divyang02** [comment]
Great. 
@gargpriyam21 can you pick up this task?

**Comment by gargpriyam21** [comment]
Yeah Sure, leave it to me 😉
